export const recipientsData = [
  {
    name: "John Doe",
    country: "USA",
    paymentMethod: "usdc",
    amount: 132,
    email: "john.doe@example.com",
    status: "pending",
  },
  {
    name: "Jane Smith",
    country: "Canada",
    paymentMethod: "usdt",
    amount: 123,
    email: "jane.smith@example.com",
    status: "pending",
  },
  {
    name: "Carlos Ruiz",
    country: "Mexico",
    paymentMethod: "stripe",
    amount: 123,
    email: "carlos.ruiz@example.com",
    status: "pending",
  },
  {
    name: "Aisha Khan",
    country: "India",
    paymentMethod: "usdt",
    amount: 133,
    email: "aisha.khan@example.com",
    status: "pending",
  },
  {
    name: "Liam Brown",
    country: "UK",
    paymentMethod: "paypal",
    amount: 123,
    email: "liam.brown@example.com",
    status: "pending",
  },
];
